### ISSUE TITLE
desktop / block element / Akkordeon / link

### ISSUE THREAD

**Issue by markus-fm** [florianmatthias/haven#4]
pls add option to ad a link at the end of the paragraph like in the "Text-Bild-Kombi" element.
![Edit Page “Seite mit allen Blöcken” ‹ Haven — WordPress 2022-06-21 at 3 35 24 PM](https://user-images.githubusercontent.com/86288680/174815539-003f2e83-c260-43d6-9823-329526b9f049.jpg)

**Comment by codeplaygoa** [comment]
Currently editor block allows you to add any link already handled the possible cases in frontend too please check.

**Comment by florianmatthiascarina** [comment]
@markus-fm the option is already there: https://share.florianmatthias.com/4gur1Zwe
but @codeplaygoa the styling is missing (default linke style = underlined, see [figma 🧩 Flexible Block elements](https://www.figma.com/file/JldevldhppT2ITfzqRXXmY/Haven?node-id=467%3A15342))
