### ISSUE TITLE
home page: flexible blocks are not shown in the frontend

### ISSUE THREAD

**Issue by florianmatthiascarina** [florianmatthias/haven#7]
currently, the blocks are indeed in the backend, but don't show up in the frontend. Hero slider also is missing, i only see one image.

![Image 2022-06-22 at 3 18 15 PM](https://user-images.githubusercontent.com/70629852/175038709-3ffe3327-cb05-45c0-8651-f41aaa51bfb7.jpg)

**Comment by markus-fm** [comment]
✅
